basePath: /
definitions:
  Server:
    properties:
      city: {type: string}
      provider: {type: string}
      public_ip: {type: string}
      state: {type: string}
      zip_code: {type: string}
    type: object
host: '[fcce:a977:eef6:442a:aaf8:0000:0000:0001]:7016'
info:
  contact: {email: james@esixteen.co, name: eSixteen.co }
  description: Get machine stats on demand for bitcoin.
  title: StatsE16
  x-21-category: utilities
  x-21-github-project-url: https://github.com/pooleja/StatsE16
  x-21-keywords: [stats, location, ram, cpu, disk, iot, sensor]
  x-21-quick-buy: "$ 21 buy http://[fcce:a977:eef6:442a:aaf8:0000:0000:0001]:7016/"
  x-21-total-price: {max: 5, min: 5}
  x-21-app-image: https://cdn.filepicker.io/api/file/xpq5tK5nSTm5ZuH2B3BW
paths:
  /:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Stats for the location and hardware of the server.
          schema:
            properties:
              server: {$ref: '#/definitions/Server'}
      summary: Returns stats about the device.
schemes: [http]
swagger: '2.0'
